<a href="https://colab.research.google.com/github/Yash0082/IGurus/blob/main/Task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Yash Adagale**

# NumPy array:
*   ### 1.Elements of an array are stored contiguously in memory.
*   ### 2.The array is by default Homogeneous {same Datatype}.
*   ### 3.Element-wise operation is possible.

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])     #Single Dimensional Numpy Array
print(a,"\n")

a = np.array([(1, 2, 3), (4, 5, 6)])  # Multi Dimensional Numpy Array
print(a,"\n")

[1 2 3] 

[[1 2 3]
 [4 5 6]] 



# Python List
* ### 1.The list can be homogeneous or heterogeneous.
* ### 2.Element-wise operation is not possible on the list.
* ### 3.Elements of a list need not be contiguous in memory.
* ### 4.dimension of list is 1D by default, n-D list are created that is 1D list in another 1D list

In [ ]:
l = ["A", "B", "C", "D"]
print(l)

['A', 'B', 'C', 'D']


In [ ]:
import sys
S= range(1000)

print("Size of each element of list in bytes: ",sys.getsizeof(S))

print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S))

D= np.arange(1000)

print("Size of each element of the Numpy array in bytes: ",D.itemsize)

print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize)

Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000
Size of each element of the Numpy array in bytes:  8
Size of the whole Numpy array in bytes:  8000


In [ ]:
import time

size = 1000000

list1 = range(size)
list2 = range(size)

array1 = np.arange(size)
array2 = np.arange(size)

initialTime = time.time()

resultantList = [(a * b) for a, b in zip(list1, list2)]

print("Time taken by Lists to perform multiplication:",
	(time.time() - initialTime),
	"seconds")

initialTime = time.time()

resultantArray = array1 * array2

print("Time taken by NumPy Arrays to perform multiplication:",
	(time.time() - initialTime),
	"seconds")


Time taken by Lists to perform multiplication: 0.3286709785461426 seconds
Time taken by NumPy Arrays to perform multiplication: 0.01708984375 seconds


In [ ]:
ls =[1, 2, 3]

arr = np.array(ls)

try:
	ls = ls + 4

except(TypeError):
	print("Lists don't support list + int")

try:
	arr = arr + 4
	print("Modified Numpy array: ",arr)

except(TypeError):
	print("Numpy arrays don't support list + int")


Lists don't support list + int
Modified Numpy array:  [5 6 7]
